# Álgebra Lineal con Python

Recordemos que si damos $n\times m$ números reales, entonces podemos crear un arreglo (una matriz):
$$A_{m\times n}=\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

y al conjunto de matrices con coeficientes en $\mathbb{R}$ lo denotamos $\text{Mat}_{m\times n}(\mathbb{R})$.


In [1]:
type(2), type(2.0), type("2") # La función type(obj) nos dice el tipo de objeto con el que se está trabajando.

(int, float, str)

### Variables
$$\text{nombre} = \text{objeto}$$

Debug: $\text{print(variable)}$

1. Suma de matrices

$$\begin{pmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{pmatrix} + \begin{pmatrix} b_{11} & b_{12} & \cdots & b_{1n} \\ b_{21} & b_{22} & \cdots & b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ b_{m1} & b_{m2} & \cdots & b_{mn} \end{pmatrix} = \begin{pmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{pmatrix}$$

2. Multiplicación de matrices

$$\begin{pmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{pmatrix} \times \begin{pmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{pmatrix} = \begin{pmatrix} a_{11}b_{11} + a_{12}b_{21} & a_{11}b_{12} + a_{12}b_{22} \\ a_{21}b_{11} + a_{22}b_{21} & a_{21}b_{12} + a_{22}b_{22} \end{pmatrix} $$

### Listas

$L=[a_{0}, a_{1}, \dots, a_{n-1}]$

In [2]:
# Vamos a generar 3 listas.
L = [1, 2, 3, 4, 5]

M = [6, 7, 8, 9 , 10]

N = [11, 12, 13]

print(L)
print(M)  # me muestra el resultado
print(N)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[11, 12, 13]


In [3]:
#  Que tipo de objeto es
type(L)

list

In [4]:
# Transformación de listas a otros objetos.
L_set = set(L)

L_set

{1, 2, 3, 4, 5}

In [5]:
L_lista = list(L_set)
L_lista

[1, 2, 3, 4, 5]

In [6]:
L + M # concatena (no realiza operaciones vectoriales).

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
L + M + N

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

### NumPy

- Un vector = arreglo 1D en Python
- Una matriz = arreglo 2D en Python

In [8]:
# LLamamos a la librería para hacer operaciones vectoriales.
import numpy as np

In [9]:
L_vector = np.array(L) # Convertir una lista en un vector. La función "np.array" es la que hace la operación.

L_vector

array([1, 2, 3, 4, 5])

In [10]:
type(L_vector)

numpy.ndarray

In [11]:
# Aquí se hace conversiones de listas a vectores.
M_vector = np.array(M)

N_vector = np.array(N)

print(M_vector)
print(N_vector)

[ 6  7  8  9 10]
[11 12 13]


In [12]:
# Con la función "len" vemos el número de elementos que tiene cada vector.
len(L_vector), len(M_vector), len(N_vector)

(5, 5, 3)

### Con esto, ya podemos sumar vectores. Únicamente cuando tienen el mismo número de elementos se puede sumar.

In [13]:
L_vector + M_vector # suma vectorial

array([ 7,  9, 11, 13, 15])

## Creando matrices con NumPy: El método `solve( , )`


Un teatro vendió $200$ entradas para un espectáculo. Las entradas de adultos cuestan $\$15$ cada una, y las entradas para niños cuestan $\$10$ cada una. En total, se recaudaron $\$2,400$. ¿Cuántas entradas de adultos y cuántas de niños se vendieron?


Definimos las variables:

* \(x\): número de entradas de adultos.
* \(y\): número de entradas de niños.


Sabemos que:

El número total de entradas vendidas es:
    \[
    x + y = 200
    \]

El total recaudado es:
    \[
    15x + 10y = 2400
    \]


Por lo tanto, el sistema de ecuaciones es:
\
\begin{aligned}
x + y &= 200, \\
15x + 10y &= 2400.
\end{aligned}
\


### Vamos a reolver este problema usando NumPy

In [14]:
# Escribimos la matriz asociada al sistema de ecuaciones.
A = np.array([1, 1, 15, 10]).reshape((2,2)) # "Reshape"  va a convertir la matriz en 2x2
A

array([[ 1,  1],
       [15, 10]])

In [15]:
# Vector de solución de sistema de ecuaciones
B = np.array([200,2400])

$$AX=B$$

## NumPy tiene una sublibrería que se llama "Linalg"en donde se pueden resolver sistemas de ecuaciones.

In [16]:
# La función "solve" resuelve el sistema de ecuaciones.
X = np.linalg.solve(A,B)

X

array([ 80., 120.])

La solución al sistema de ecuaciones es:
x=80
y=120